### ISSUE TITLE
Estimate cost of implementing facility to add and remove words on the fly

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/gnmatcher#4]

**Comment by alexander-myltsev** [comment]
[liblevenshtein-java](https://github.com/universal-automata/liblevenshtein-java) uses [Direct Acyclic Word Graph (DAWG)](http://stevehanov.ca/blog/index.php?id=115) as compact internal storage of all input words. Currently it ascendingly sorts input dictionary, and then sequentially adds them to DAWG. That means that DAWG structure should be improved to accept a string. I suppose the estimation is 5.
